version: "2"
services:
  db:
    image: "postgres"
    expose:
      - "5432"

  proxy:
    image: "tt/nginx"
    build: nginx
    ports:
      - "80:8080"
    links:
      - web
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=web

  web:
    image: "tt/rails"
    build: rails
    command: rails server --port 3000 --binding "0.0.0.0"
    expose:
      - "3000"
    links:
      - db
